### ISSUE TITLE
plugin not loading in Cura

### ISSUE THREAD

**Issue by scanlight** [Sakati84/3DPrintColorizer#111]
Hi all having some issues with loading the plugin to cura. 

Copied the py script to the plugin folder stated in the instruction and restarted Cura. still the plugin doesnt show up in the plugin list.
Tried cura 2.4, 4.9.0, 4.9.1 5.2 and 5.3

Is this script version specific or some other issue ?
What version is best used?

Hope somebody can point me in the right direction after printing all the parts haha. 👍

**Comment by LouisLe18** [comment]
I used 4.9.0 and it loaded. But I'm still trying to get it to print properly

**Comment by scanlight** [comment]
checking the logs it has an issue (line 73) with the title starting with a decimal. changed this and tried again. 
now issue at line 8
 !DOCTYPE html     (removed the brackets to post here)
  ^
 SyntaxError: invalid syntax
 
 
 update: tried 4.9 version and the same problem

**Comment by scanlight** [comment]
full Log part with error:

2023-03-17 19:27:53,229 - ERROR - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [221]: Exception: Exception occurred while loading post processing plugin: invalid syntax (PenColorizer.py, line 8)
2023-03-17 19:27:53,229 - ERROR - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [221]: Traceback (most recent call last):
2023-03-17 19:27:53,230 - ERROR - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [221]:   File "C:\Program Files\UltiMaker Cura 5.3.0\share\cura\plugins\PostProcessingPlugin\PostProcessingPlugin.py", line 201, in loadScripts
2023-03-17 19:27:53,230 - ERROR - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [221]:     spec.loader.exec_module(loaded_script)  # type: ignore
2023-03-17 19:27:53,230 - ERROR - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [221]:   File "<frozen importlib._bootstrap_external>", line 879, in exec_module
2023-03-17 19:27:53,231 - ERROR - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [221]:   File "<frozen importlib._bootstrap_external>", line 1017, in get_code
2023-03-17 19:27:53,231 - ERROR - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [221]:   File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
2023-03-17 19:27:53,231 - ERROR - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [221]:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2023-03-17 19:27:53,232 - ERROR - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [221]:   File "C:\Users\robbert\AppData\Roaming\cura\5.3\scripts\PenColorizer.py", line 8
2023-03-17 19:27:53,232 - ERROR - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [221]:     <!DOCTYPE html>
2023-03-17 19:27:53,232 - ERROR - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [221]:     ^
2023-03-17 19:27:53,233 - ERROR - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [221]: SyntaxError: invalid syntax
2023-03-17 19:27:53,234 - ERROR - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [221]: Exception: Exception occurred while loading post processing plugin: invalid syntax (PenColorizer.py, line 8)
2023-03-17 19:27:53,235 - ERROR - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [221]: Traceback (most recent call last):
2023-03-17 19:27:53,235 - ERROR - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [221]:   File "C:\Program Files\UltiMaker Cura 5.3.0\share\cura\plugins\PostProcessingPlugin\PostProcessingPlugin.py", line 201, in loadScripts
2023-03-17 19:27:53,235 - ERROR - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [221]:     spec.loader.exec_module(loaded_script)  # type: ignore
2023-03-17 19:27:53,236 - ERROR - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [221]:   File "<frozen importlib._bootstrap_external>", line 879, in exec_module
2023-03-17 19:27:53,236 - ERROR - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [221]:   File "<frozen importlib._bootstrap_external>", line 1017, in get_code
2023-03-17 19:27:53,236 - ERROR - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [221]:   File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
2023-03-17 19:27:53,237 - ERROR - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [221]:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2023-03-17 19:27:53,237 - ERROR - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [221]:   File "C:\Users\robbert\AppData\Roaming\cura\5.3\scripts\PenColorizer.py", line 8
2023-03-17 19:27:53,237 - ERROR - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [221]:     <!DOCTYPE html>
2023-03-17 19:27:53,238 - ERROR - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [221]:     ^
2023-03-17 19:27:53,238 - ERROR - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [221]: SyntaxError: invalid syntax

**Comment by scanlight** [comment]
solved! thnks
